version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'drinks'
      MYSQL_USER: 'sistema'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
             --default-authentication-plugin=mysql_native_password
             --init-file /docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    environment:
      DB_HOSTNAME: 'localhost'
      DB_PASSWORD: ''
      DB_USER: 'sistema'
      DB_DATABASE: 'drinks'
    ports:
      - "80:8080"

volumes:
  my-db:
