basePath: /
info:
  contact: {}
paths:
  /cocktail:
    get:
      consumes:
      - application/json
      description: get one IBA Cocktail
      produces:
      - application/json
      responses: {}
      summary: get Cocktail by Id
    post:
      consumes:
      - application/json
      description: Add IBA Cocktail
      parameters:
      - in: formData
        name: garnish
        type: string
      - in: formData
        name: id
        type: integer
      - in: formData
        name: ingredients
        type: string
      - in: formData
        name: method
        type: string
      - in: formData
        name: name
        type: string
      produces:
      - application/json
      responses: {}
      summary: Add Cocktail
  /cocktails:
    get:
      consumes:
      - application/json
      description: List IBA Cocktails
      produces:
      - application/json
      responses: {}
      summary: List Cocktails
swagger: "2.0"
